on: push
name: Update develop branch on push to main
jobs:
  updateBranch:
    name: Update develop branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: Embraser01/update-git-branch-action@v1.0.0
      if: github.ref == 'refs/heads/main'
      with:
        branch: develop
        githubToken: ${{ secrets.PAT_TOKEN }} # Github Token
